services:
  test:
    container_name: "test_cont"
    image: "ghoshbishal/test1:latest"
    ports:
      - 8080:8080
  db:
    container_name: "mysqlDb"
    restart: always
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_security_test
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent